# Generated by Django 3.0.1 on 2020-02-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='coordinateLB',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='coordinateUB',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='demandLB',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='demandUB',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='faciFailProb',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='fixedCostLB',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='fixedCostUB',
            field=models.FloatField(default=None),
        ),
    ]
