# Generated by Django 3.0.1 on 2020-02-17 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20200205_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReliableFLPInstancesSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=50)),
                ('file_data', models.FileField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='pwd',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='user',
        ),
    ]
